# Generated by Django 3.1.2 on 2020-10-18 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amphoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amphoe_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_name', models.CharField(max_length=70)),
                ('Place_content', models.TextField()),
                ('Amphoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.amphoe')),
            ],
        ),
    ]
