# Generated by Django 3.1.2 on 2020-10-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='PathImage',
            field=models.CharField(default='', max_length=70),
        ),
    ]
