# Generated by Django 3.1.2 on 2020-10-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_pathimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='PathImage',
            field=models.CharField(default='', max_length=200),
        ),
    ]
