# Generated by Django 3.1.2 on 2020-10-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20201024_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Latitude',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='Loggitude',
            field=models.CharField(default='', max_length=50),
        ),
    ]
