# Generated by Django 3.1.2 on 2020-10-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20201028_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Latitude',
            field=models.CharField(default=int, max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='Loggitude',
            field=models.CharField(default=int, max_length=50),
        ),
    ]
