# Generated by Django 3.1.2 on 2020-10-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20201028_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Loggitude',
            new_name='Longitude',
        ),
    ]
