# Generated by Django 3.1.2 on 2020-10-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20201028_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='Longitude',
            field=models.FloatField(),
        ),
    ]
