# Generated by Django 3.1.2 on 2020-10-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_auto_20201028_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Longitude',
        ),
    ]
