# Generated by Django 3.1.2 on 2020-10-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20201028_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_name', models.CharField(max_length=70)),
                ('Place_content', models.TextField()),
                ('PathImage', models.CharField(default='', max_length=200)),
                ('Amphoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.amphoe')),
            ],
        ),
    ]
