# Generated by Django 3.1.2 on 2020-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='PathImage',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='PathImage',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
